<h1>Chargify / Zend Framework Sample App</h1>

<p style="text-align:center">Developed by <a href="http://www.crucialwebstudio.com/chargify?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">Crucial Web Studio</a>. 
Visit the <a href="http://www.crucialwebstudio.com/made/chargify-sample-app?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">project page</a>.</p>
<p style="text-align:center">Want to host a customer facing portal on your own server? Check out <a href="http://www.crucialwebstudio.com/made/crucial-app?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">Crucial App</a>.</p>

<div style="width: 424px; margin: auto">
  <img src="/images/logo_crucial.png" width="424" height="144" />
</div>