<div class="inner">
    <p>This sample app created by <span><a href="http://www.crucialwebstudio.com/chargify?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">Crucial Web Studio</a></span> using <span><a href="http://www.zendframework.com" target="_blank">Zend Framework</a></span>.</p>
    <p>API and interface design by <span><a href="http://chargify.com" target="_blank">Chargify</a></span>.</p>
    <p><span><a href="http://docs.chargify.com/" target="_blank">Chargify API Documentation</a></span></p>
</div>