<ul id="seller_menu">
  <li class="first"><a href="http://www.crucialwebstudio.com/chargify?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">Crucial Web Studio</a></li>
  <li><a href="http://www.crucialwebstudio.com/made/crucial-app?utm_source=Chargify%20Sample%20App&utm_medium=Download&utm_campaign=Open%20Source" target="_blank">Crucial App | Customer Facing Portal</a></li>
</ul>