<h1>An error occurred</h1>


<h2><?php echo $this->message ?></h2>
  
<?php if (isset($this->exception)): ?>
  <h3>Exception information:</h3>
  
  <p><b>Type:</b> <?php echo get_class($this->exception) ?></p>
  
  <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
  
  <p><b>Code:</b> <?php echo $this->exception->getCode() ?></p>

  <h3>Stack trace:</h3>
  <div>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>
  </div>
  
  <h3>$this-&gt;request-&gt;getParams()</h3>
  <div>
    <pre><?php var_dump($this->request->getParams()) ?></pre>
  </div>
<?php endif; ?>

<h3>$_ENV</h3>
<div>
  <pre><?php var_dump($_ENV) ?></pre>
</div>

<h3>$_GET</h3>
<div>
  <pre><?php var_dump($_GET) ?></pre>
</div>

<h3>$_POST</h3>
<div>
  <pre><?php var_dump($_POST) ?></pre>
</div>

<h3>$_COOKIE</h3>
<div>
  <pre><?php var_dump($_COOKIE) ?></pre>
</div>

<h3>$_SESSION</h3>
<div>
  <pre><?php !empty($_SESSION) ? var_dump($_SESSION) : ''; ?></pre>
</div>

<h3>$_SERVER</h3>
<div>
  <pre><?php var_dump($_SERVER) ?></pre>
</div>
